{% set name = "aiochclient" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7140739163bfaf0e90839552cda53b4ea7b37110b0d3a26ccd00f055d0a81b4b

build:
  number: 0
  skip: True  # [win]
  skip: True  # [py<36]
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  build:
    - "{{ compiler('c') }}"
  host:
    - cython
    - pip
    - python
  run:
    - aiohttp >=3.0.1
    - python
    - ciso8601  # [py<37]

test:
  imports:
    - aiochclient

about:
  home: "https://github.com/maximdanilchenko/aiochclient"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Async http clickhouse client for python 3.6+"
  doc_url: "https://aiochclient.readthedocs.io/"

extra:
  recipe-maintainers:
    - xhochy
